### ISSUE TITLE
[TODO] [services] Migrate from Android makefiles to Android blueprints

### ISSUE THREAD

**Issue by Lyudmila17** [TeamSoviet/android_device_motorola_athene#1]

**Comment by penn5** [comment]
Yep I agree this needs doing. But for now, ninja and ckati can work it all out for us...

**Comment by Lyudmila17** [comment]
Nah this sounds stupid, I'll see what I do someday.

**Comment by penn5** [comment]
Btw there's a tool called androidmk, it's really useful.
